<?php

namespace GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador;

use GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Condicion\Condicion;
use GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Condicion\ICondicionFabrica;
use GT\Libs\Sistema\BD\Conexion\Conexion;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Clausula;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\IClausulaFabrica;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Comando\ComandoDmlMock;
use PHPUnit_Framework_TestCase;
use Phpunit_Util;
//******************************************************************************




/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-26 at 14:51:55.
 */
class LogicoTest extends PHPUnit_Framework_TestCase
{
    use Phpunit_Util;
//******************************************************************************

    /**
     * @var Logico
     */
    protected $object;

    /**
     * @var ComandoDmlMock
     */
    private $helper = null;

    /**
     * @var IClausulaFabrica
     */
    private $clausula_fabrica = null;

    /**
     * @var Conexion
     */
    private $conexion = null;

    /**
     * @var Clausula
     */
    private $clausula = null;

    /**
     * @var ICondicionFabrica
     */
    private $fabrica_condiciones = null;





    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->helper = new ComandoDmlMock();

        $this->conexion = $this->helper->getConexionMock(['prepare']);
        $this->clausula_fabrica = $this->helper->getClausulasFabrica();
        $this->fabrica_condiciones = $this->helper->getCondicionesFabricaMock();
        $comando = $this->helper->getComandoMock($this->conexion, $this->clausula_fabrica, $this->fabrica_condiciones);
        $this->clausula = $this->helper->getClausulaMock($comando, $this->fabrica_condiciones, true);

        $this->object = $this->getMockBuilder(Logico::class)
                                ->setConstructorArgs([$this->clausula, $this->fabrica_condiciones])
                                ->getMockForAbstractClass();
    }
//******************************************************************************


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
//******************************************************************************



// <editor-fold defaultstate="collapsed" desc=" Tests para la función: getCondicion ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::getCondicion
     * @group getCondicion
     */
    public function testGetCondicion()
    {
        $expects = $this->getMockBuilder(Condicion::class)
                        ->disableOriginalConstructor()
                        ->getMockForAbstractClass();

        $this->propertyEdit($this->object, 'condicion', $expects);

        $resultado = $this->object->getCondicion();

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

// </editor-fold>

// <editor-fold defaultstate="collapsed" desc=" Tests para la función: setCondicion ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::setCondicion
     * @group setCondicion
     */
    public function testSetCondicion()
    {
        $condicion = $this->getMockBuilder(Condicion::class)
                        ->disableOriginalConstructor()
                        ->getMockForAbstractClass();

        $this->object->setCondicion($condicion);

        $this->assertEquals($condicion, $this->object->getCondicion(),
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

// </editor-fold>

// <editor-fold defaultstate="collapsed" desc=" Tests para la función: getFabricaCondiciones ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::getFabricaCondiciones
     * @group getFabricaCondiciones
     */
    public function testGetFabricaCondiciones()
    {
        $expects = $this->fabrica_condiciones;

        $resultado = $this->invocar($this->object, 'getFabricaCondiciones');

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

// </editor-fold>


// <editor-fold defaultstate="collapsed" desc=" Tests para la función: condicionCrear ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_IN()
    {
        $atributo = 'atributo';
        $tipo = OP::IN;
        $valor = [1, 2, 3];

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getIn')
                                    ->with($this->clausula, $atributo, $tipo, $valor)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo, $valor);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_NOT_IN()
    {
        $atributo = 'atributo';
        $tipo = OP::NOT_IN;
        $valor = [1, 2, 3];

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getIn')
                                    ->with($this->clausula, $atributo, $tipo, $valor)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo, $valor);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_IS_NULL()
    {
        $atributo = 'atributo';
        $tipo = OP::IS_NULL;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getIs')
                                    ->with($this->clausula, $atributo, $tipo)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_IS_NOT_NULL()
    {
        $atributo = 'atributo';
        $tipo = OP::IS_NOT_NULL;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getIs')
                                    ->with($this->clausula, $atributo, $tipo)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_IS_TRUE()
    {
        $atributo = 'atributo';
        $tipo = OP::IS_TRUE;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getIs')
                                    ->with($this->clausula, $atributo, $tipo)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************


    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_IS_FALSE()
    {
        $atributo = 'atributo';
        $tipo = OP::IS_FALSE;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getIs')
                                    ->with($this->clausula, $atributo, $tipo)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_BETWEEN()
    {
        $atributo = 'atributo';
        $tipo = OP::BETWEEN;
        $ini = 3;
        $fin = 10;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getBetween')
                                    ->with($this->clausula, $atributo, $tipo, $ini, $fin)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo, $ini, $fin);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_NOT_BETWEEN()
    {
        $atributo = 'atributo';
        $tipo = OP::NOT_BETWEEN;
        $ini = 3;
        $fin = 10;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getBetween')
                                    ->with($this->clausula, $atributo, $tipo, $ini, $fin)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo, $ini, $fin);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\Logico::condicionCrear
     * @group condicionCrear
     */
    public function testCondicionCrear__condicion_EQUAL()
    {
        $atributo = 'atributo';
        $tipo = OP::EQUAL;
        $valor = 3;

        $condicion = $this->getMockBuilder(Condicion::class)
                            ->disableOriginalConstructor()
                            ->getMockForAbstractClass();

        $this->fabrica_condiciones->expects($this->once())
                                    ->method('getComparacion')
                                    ->with($this->clausula, $atributo, $tipo, $valor)
                                    ->will($this->returnValue($condicion));

        $this->object->condicionCrear($atributo, $tipo, $valor);

        $resultado = $this->propertyEdit($this->object, 'condicion')->getValue($this->object);
        $this->assertEquals($condicion, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

// </editor-fold>

}