<?php

declare(strict_types=1);

namespace Tests\Unit\Sql\Comando\Mysql\Condicion;

use GT\Libs\Sistema\BD\QueryConstructor\Comando\Operador\OP;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Clausula;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\ClausulaFabricaInterface;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Comando\ComandoDmlMock;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\ComandoMock;
use PHPUnit\Framework\TestCase;
use Phpunit\Util;

// ******************************************************************************

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-26 at 14:51:55.
 */
class MysqlCondicionFabricaTest extends TestCase
{
    use Util;
    // ******************************************************************************

    /**
     * @var MysqlCondicionFabrica
     */
    protected $object;

    /**
     * @var ComandoDmlMock
     */
    private $helper;

    /**
     * @var ClausulaFabricaInterface
     */
    private $clausula_fabrica;

    /**
     * @var Clausula
     */
    private $clausula;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->helper = new ComandoMock();

        $conexion = $this->helper->getConexionMock();
        $this->clausula_fabrica = $this->helper->getClausulasFabrica();
        $fabrica_condiciones = $this->helper->getCondicionesFabricaMock();
        $comando = $this->helper->getComandoMock($conexion, $this->clausula_fabrica, $fabrica_condiciones);

        $this->clausula = $this->helper->getClausulaMock($comando, $fabrica_condiciones, true);

        $this->object = new MysqlCondicionFabrica();
    }
    // ******************************************************************************

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    // ******************************************************************************

    // <editor-fold defaultstate="collapsed" desc=" Tests para la función: getBetween ">

    /**
     * @covers \GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Condicion\MysqlCondicionFabrica::getBetween
     *
     * @group getBetween
     */
    public function testGetBetween()
    {
        $resultado = $this->object->getBetween($this->clausula, 'atributo', OP::BETWEEN, 0, 10);

        $this->assertInstanceOf(Between::class, $resultado,
            'ERROR: el objeto creado no es el esperado');
    }
    // ******************************************************************************

    /**
     * @covers \GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Condicion\MysqlCondicionFabrica::getComparacion
     *
     * @group getComparacion
     */
    public function testGetComparacion()
    {
        $resultado = $this->object->getComparacion($this->clausula, 'atributo', OP::EQUAL, 10);

        $this->assertInstanceOf(Comparacion::class, $resultado,
            'ERROR: el objeto creado no es el esperado');
    }
    // ******************************************************************************

    /**
     * @covers \GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Condicion\MysqlCondicionFabrica::getIn
     *
     * @group getIn
     */
    public function testGetIn()
    {
        $resultado = $this->object->getIn($this->clausula, 'atributo', OP::EQUAL, [10, 3]);

        $this->assertInstanceOf(In::class, $resultado,
            'ERROR: el objeto creado no es el esperado');
    }
    // ******************************************************************************

    /**
     * @covers \GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Condicion\MysqlCondicionFabrica::getIs
     *
     * @group getIs
     */
    public function testGetIs()
    {
        $resultado = $this->object->getIs($this->clausula, 'atributo', OP::IS_TRUE);

        $this->assertInstanceOf(Is::class, $resultado,
            'ERROR: el objeto creado no es el esperado');
    }
    // ******************************************************************************

    // </editor-fold>
}
