<?php

namespace GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete;

use GT\Libs\Sistema\BD\QueryConstructor\Comando\Comando\Comando;
use GT\Libs\Sistema\BD\Conexion\Conexion;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Delete\DeleteParams;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\IClausulaFabrica;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\TIPOS;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Comando\ComandoDmlMock;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\ComandoMock;
use PHPUnit_Framework_TestCase;
use Phpunit_Util;
//******************************************************************************




/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-26 at 14:51:55.
 */
class DeleteTest extends PHPUnit_Framework_TestCase
{
    use Phpunit_Util;
//******************************************************************************

    /**
     * @var Delete
     */
    private $object = null;

    /**
     * @var ComandoDmlMock
     */
    private $helper = null;

    /**
     * @var IClausulaFabrica
     */
    private $clausula_fabrica = null;


    /**
     * @var Comando
     */
    private $comando = null;

    /**
     * @var Conexion
     */
    private $conexion = null;





    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->helper = new ComandoMock();

        $this->conexion = $this->helper->getConexionMock(['quote']);
        $this->clausula_fabrica = $this->helper->getClausulasFabrica();
        $fabrica_condiciones = $this->helper->getCondicionesFabricaMock();
        $this->comando = $this->helper->getComandoMock($this->conexion, $this->clausula_fabrica, $fabrica_condiciones, ['getConexion']);

        $this->object = new Delete($this->comando, $fabrica_condiciones, false);
    }
//******************************************************************************


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
//******************************************************************************


// <editor-fold defaultstate="collapsed" desc=" Tests para la función: tipo de claúsula ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::generar
     * @group generar
     */
    public function testGenerar__Tipo_de_clausula()
    {
        $tipo = $this->propertyEdit($this->object, 'tipo')->getValue($this->object);
        $this->assertEquals(TIPOS::DELETE, $tipo,
            'ERROR: la clausual no es del tipo esperado');
    }
//******************************************************************************

// </editor-fold>


// <editor-fold defaultstate="collapsed" desc=" Tests para la función: generar ">



    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::generar
     * @group generar
     */
    public function testGenerar__Una_tabla_sin_tablas_de_referencia()
    {
        $expects = 'DELETE ' . MODIFICADORES::IGNORE . ' ' . MODIFICADORES::LOW_PRIORITY .
                    ' FROM tabla_eliminar1';

        $param = new DeleteParams();
        $param->tablas_eliminar = ['tabla_eliminar1'];
        $param->tablas_referencia = [];
        $param->modificadores = [MODIFICADORES::IGNORE, MODIFICADORES::LOW_PRIORITY];

        $this->object->setParams($param);

        $resultado = $this->object->generar();

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************


    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::generar
     * @group generar
     */
    public function testGenerar__Varias_tablas_sin_tablas_de_referencia()
    {
        $expects = 'DELETE ' . MODIFICADORES::IGNORE . ' ' . MODIFICADORES::LOW_PRIORITY .
                    ' FROM tabla_eliminar1, tabla_eliminar2';

        $param = new DeleteParams();
        $param->tablas_eliminar = ['tabla_eliminar1', 'tabla_eliminar2'];
        $param->tablas_referencia = [];
        $param->modificadores = [MODIFICADORES::IGNORE, MODIFICADORES::LOW_PRIORITY];

        $this->object->setParams($param);

        $resultado = $this->object->generar();

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::generar
     * @group generar
     */
    public function testGenerar__Una_tabla_con_una_tabla_de_referencia()
    {
        $expects = 'DELETE ' . MODIFICADORES::IGNORE . ' ' . MODIFICADORES::LOW_PRIORITY .
                    ' tabla_eliminar1' .
                    ' FROM tabla_referencia1';

        $param = new DeleteParams();
        $param->tablas_eliminar = ['tabla_eliminar1'];
        $param->tablas_referencia = ['tabla_referencia1'];
        $param->modificadores = [MODIFICADORES::IGNORE, MODIFICADORES::LOW_PRIORITY];

        $this->object->setParams($param);

        $resultado = $this->object->generar();

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************


    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::generar
     * @group generar
     */
    public function testGenerar__Una_tabla_con_tablas_de_referencia()
    {
        $expects = 'DELETE ' . MODIFICADORES::IGNORE . ' ' . MODIFICADORES::LOW_PRIORITY .
                    ' tabla_eliminar1' .
                    ' FROM tabla_referencia1, tabla_referencia2';

        $param = new DeleteParams();
        $param->tablas_eliminar = ['tabla_eliminar1'];
        $param->tablas_referencia = ['tabla_referencia1', 'tabla_referencia2'];
        $param->modificadores = [MODIFICADORES::IGNORE, MODIFICADORES::LOW_PRIORITY];

        $this->object->setParams($param);

        $resultado = $this->object->generar();

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::generar
     * @group generar
     */
    public function testGenerar__Varias_tablas_con_tablas_de_referencia()
    {
        $expects = 'DELETE ' . MODIFICADORES::IGNORE . ' ' . MODIFICADORES::LOW_PRIORITY .
                    ' tabla_eliminar1, tabla_eliminar2' .
                    ' FROM tabla_referencia1, tabla_referencia2';

        $param = new DeleteParams();
        $param->tablas_eliminar = ['tabla_eliminar1', 'tabla_eliminar2'];
        $param->tablas_referencia = ['tabla_referencia1', 'tabla_referencia2'];
        $param->modificadores = [MODIFICADORES::IGNORE, MODIFICADORES::LOW_PRIORITY];

        $this->object->setParams($param);

        $resultado = $this->object->generar();

        $this->assertEquals($expects, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

// </editor-fold>


// <editor-fold defaultstate="collapsed" desc=" Tests para la función: getRetornoCampos ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\Mysql\Clausulas\Delete\Delete::getRetornoCampos
     * @group getRetornoCampos
     */
    public function testGetRetornoCampos()
    {
        $resultado = $this->object->getRetornoCampos();

        $this->assertInternalType('array', $resultado,
            'ERROR: el valor devulto no es un array');

        $this->assertEmpty($resultado,
            'ERROR: Se esperaba que el valor devuelto fuera un array vacío');
    }
//******************************************************************************

// </editor-fold>
}