<?php

namespace GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Sql;

use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\ClausulaMock;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\IClausulaFabrica;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Sql\SqlClausula;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Sql\SqlParams;
use GT\Libs\Sistema\BD\QueryConstructor\Sql\Comando\ComandoMock;
use PHPUnit_Framework_TestCase;
use Phpunit_Util;
//******************************************************************************




/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-03-26 at 14:51:55.
 */
class SqlClausulaTest extends PHPUnit_Framework_TestCase
{
    use Phpunit_Util;
//******************************************************************************

    /**
     * @var FromClausula
     */
    protected $object;

    /**
     *
     * @var ClausulaMock
     */
    private $clausula_mock = null;

    /**
     * @var IClausulaFabrica
     */
    private $clausula_fabrica = null;




    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->clausula_mock = new ComandoMock();

        $conexion = $this->clausula_mock->getConexionMock();
        $this->clausula_fabrica = $this->clausula_mock->getClausulasFabrica();
        $fabrica_condiciones = $this->clausula_mock->getCondicionesFabricaMock();
        $comando = $this->clausula_mock->getComandoMock($conexion, $this->clausula_fabrica, $fabrica_condiciones);

        $this->object = $this->getMockBuilder(SqlClausula::class)
                                ->setConstructorArgs([$comando, $fabrica_condiciones, false])
                                ->getMockForAbstractClass();
    }
//******************************************************************************


    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }
//******************************************************************************



// <editor-fold defaultstate="collapsed" desc=" Tests para la función: generar ">

    /**
     * @covers GT\Libs\Sistema\BD\QueryConstructor\Sql\Clausula\Sql\SqlClausula::generar
     * @group generar
     */
    public function testGenerar__genera_el_comando_sql()
    {
        $expect = new SqlParams();
        $expect->sql = 'SELECT * FROM usuarios';
        $this->propertyEdit($this->object, 'params', $expect);

        $resultado = $this->object->generar();

        $this->assertEquals($expect->sql, $resultado,
            'ERROR: el valor devuelto no es el esperado');
    }
//******************************************************************************

// </editor-fold>
}